#ifndef MCU_CONFIG_H
#define MCU_CONFIG_H

#define SOFTWARE_NAME "E1_Panel"
#define SOFTWARE_VERSION "v1.0.0"
#define SOFTWARE_BUILD_DATE __DATE__
#define SOFTWARE_BUILD_TIME __TIME__
#define HARDWARE_VERSION "v1.0.0"

#endif